### ISSUE TITLE
Error when trying to reuse volume

### ISSUE THREAD

**Issue by ruanbekker** [flaviostutz/cepher#8] opened 2019-05-19 11:21 UTC
First off, great plugin!

### Issue

when I try to reuse the volume I get this error:

```
$ docker-compose up -d
Creating network "app_default" with the default driver
ERROR: Configuration for volume volumes/voltest specifies driver cepher, but a volume with the same name uses a different driver (cepher:latest). If you wish to use the new configuration, please remove the existing volume "volumes/voltest" first:
$ docker volume rm volumes/voltest
```

### Demonstration:

My compose:

```
$ cat docker-compose.yml
version: '3.6'
services:
  test:
    image: alpine
    volumes:
      - voltest:/data
    command: ping localhost

volumes:
  voltest:
    driver: cepher
    name: "volumes/voltest"
```

Initial create works fine:

```
$ docker-compose up -d
Creating volume "volumes/voltest" with cepher driver
Creating app_test_1 ... done
```

Exec into container and create something:

```
$ docker-compose exec test sh
/ # echo $(hostname) > /data/file.txt
/ # cat /data/file.txt
02c154188cf5
/ # exit
```

Bring down the stack from compose:

```
$ docker-compose down
Stopping app_test_1 ... done
Removing app_test_1 ... done
Removing network app_default
```

Now when I try to bring it up again it fails:

```
$ docker-compose up -d
Creating network "app_default" with the default driver
ERROR: Configuration for volume volumes/voltest specifies driver cepher, but a volume with the same name uses a different driver (cepher:latest). If you wish to use the new configuration, please remove the existing volume "volumes/voltest" first:
$ docker volume rm volumes/voltest
```

Is it perhaps my compose config that's incorrect? Also, I have spun up the ceph stack from the readme that you provided.

**Comment by flaviostutz** [comment] 2019-05-19 16:08
Thanks for the issue description.

I’ve already tested the scenario you provided before and it worked...

@jairsjunior, any clues on this?

Which Docker version and which Linux distribution are you using?

**Comment by jairsjunior** [comment] 2019-06-18 13:10
Hi @ruanbekker!

I changed some things at the project and i reproduced your scenario after the changes and i don't had this problems anymore. Can you try again to verify if the problem persists?

The new image of plugin is at my docker hub account  
You can install using this command changing the variables to your ceph hosts.

```
docker plugin install jairsjunior/cepher:0.0.1-alpha \
  --grant-all-permissions \
  --alias=cepher \
  MONITOR_HOSTS="${HOST_1}:6789,${HOST_2}:6789,${HOST_3}:6789" \
  ETCD_URL="http://${HOST_1}:2379,http://${HOST_2}:2379,http://${HOST_3}:2379" \
  DEFAULT_IMAGE_SIZE=100 \
```

If the problem persists, please let me know.

**Comment by flaviostutz** [comment] 2019-07-23 19:16
Closing as it seems to be solved.

**Closed by flaviostutz** 2019-07-23 19:16 UTC
